baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.141.0"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.parser.attribute]
  block = true

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [["$$", "$$"]]
    inline = [["$", "$"]]

# this doesn't propagate to the site but putting it here too
[markup.highlight]
  noClasses = false
