name = 'hugo-tufte-ish'
license = 'MIT'
licenselink = 'https://github.com/axolotls73/blog-theme/blob/main/LICENSE'
# description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/axolotls73/blog-theme'

# If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'

# Taxonomy terms
# tags = ['blog', 'company']
# features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Emily Tucker'
  homepage = 'https://axolotls73.github.io/'
