name = 'Theme name'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/axolotls73/blog-theme'

# If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'

# Taxonomy terms
# tags = ['blog', 'company']
# features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Emily Tucker'
  homepage = 'https://axolotls73.github.io/'

# If porting an existing theme
[original]
  author = "Shawn O'Hare"
  homepage = 'http://www.shawnohare.com'
  repo = 'https://github.com/loikein/hugo-tufte'
